In [15]:
import torch
import numpy as np

In [16]:
np.random.seed(42)


In [17]:
arr = np.random.randint(0, 5, 6)
x = torch.tensor(arr, dtype=torch.int64).reshape(3, 2)

In [18]:
y_values = np.random.randint(0, 5, 6)
y = torch.tensor(y_values, dtype=torch.int64).reshape(2, 3)

In [19]:
matrix_product = torch.mm(x, y)


In [20]:
print("Tensor x:\n", x)


Tensor x:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [21]:
print("Shape of x:", x.shape)


Shape of x: torch.Size([3, 2])


In [22]:
print("\nTensor y:\n", y)



Tensor y:
 tensor([[2, 2, 2],
        [4, 3, 2]])


In [23]:
print("Shape of y:", y.shape)


Shape of y: torch.Size([2, 3])


In [24]:
print("\nMatrix Product (x @ y):\n", matrix_product)



Matrix Product (x @ y):
 tensor([[22, 18, 14],
        [20, 16, 12],
        [12, 11, 10]])


In [25]:
print("Shape of Result:", matrix_product.shape)


Shape of Result: torch.Size([3, 3])
